### ISSUE TITLE
ValueError: invalid literal for int() with base 10: 'MIG-cfb2a8ae-864b-50df-94a5-98983023f29d'

### ISSUE THREAD

**Issue by liwd190019** [OpenRLHF/OpenRLHF#402]
Hello, I came across an error `ValueError: invalid literal for int() with base 10: 'MIG-cfb2a8ae-864b-50df-94a5-98983023f29d'`. 
My `nvidia-smi` result is:
```
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA A100 80GB PCIe          On  |   00000000:E3:00.0 Off |                   On |
| N/A   31C    P0             41W /  300W |      74MiB /  81920MiB |     N/A      Default |
|                                         |                        |              Enabled |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| MIG devices:                                                                            |
+------------------+----------------------------------+-----------+-----------------------+
| GPU  GI  CI  MIG |                     Memory-Usage |        Vol|      Shared           |
|      ID  ID  Dev |                       BAR1-Usage | SM     Unc| CE ENC DEC OFA JPG    |
|                  |                                  |        ECC|                       |
|==================+==================================+===========+=======================|
|  0    1   0   0  |              37MiB / 40192MiB    | 42      0 |  3   0    2    0    0 |
|                  |                 0MiB / 65535MiB  |           |                       |
+------------------+----------------------------------+-----------+-----------------------+
                                                                                         
+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|  No running processes found                                                             |
+-----------------------------------------------------------------------------------------+
```
```
+ read -r -d '' training_commands
+ [[ '' != \s\l\u\r\m ]]
+ deepspeed --module openrlhf.cli.train_sft --max_len 2048 --dataset Open-Orca/OpenOrca --input_key question --output_key response --train_batch_size 256 --micro_train_batch_size 2 --max_samples 5000 --pretrain /nfs/turbo/coe-mih/shared_data/meta-llama/meta-llama3.1-8B --save_path ./checkpoint/llama3-8b-sft --save_steps -1 --logging_steps 1 --eval_steps -1 --zero_stage 2 --max_epochs 1 --bf16 --flash_attn --learning_rate 5e-6 --load_checkpoint --gradient_checkpointing
[2024-08-03 00:19:39,425] [INFO] [real_accelerator.py:203:get_accelerator] Setting ds_accelerator to cuda (auto detect)
 [WARNING]  async_io requires the dev libaio .so object and headers but these were not found.
 [WARNING]  async_io: please install the libaio-dev package with apt
 [WARNING]  If libaio is already installed (perhaps from source), try setting the CFLAGS and LDFLAGS environment variables to where it can be found.
 [WARNING]  Please specify the CUTLASS repo directory as environment variable $CUTLASS_PATH
 [WARNING]  sparse_attn requires a torch version >= 1.5 and < 2.0 but detected 2.4
 [WARNING]  using untested triton version (3.0.0), only 1.0.0 is known to be compatible
/home/wdli/scratch/miniconda3/envs/openrlhf/lib/python3.11/site-packages/deepspeed/runtime/zero/linear.py:47: FutureWarning: `torch.cuda.amp.custom_fwd(args...)` is deprecated. Please use `torch.amp.custom_fwd(args..., device_type='cuda')` instead.
  @autocast_custom_fwd
/home/wdli/scratch/miniconda3/envs/openrlhf/lib/python3.11/site-packages/deepspeed/runtime/zero/linear.py:66: FutureWarning: `torch.cuda.amp.custom_bwd(args...)` is deprecated. Please use `torch.amp.custom_bwd(args..., device_type='cuda')` instead.
  @autocast_custom_bwd
[2024-08-03 00:20:06,671] [WARNING] [runner.py:202:fetch_hostfile] Unable to find hostfile, will proceed with training with local resources only.
Detected CUDA_VISIBLE_DEVICES=MIG-cfb2a8ae-864b-50df-94a5-98983023f29d: setting --include=localhost:MIG-cfb2a8ae-864b-50df-94a5-98983023f29d
Traceback (most recent call last):
  File "/home/wdli/scratch/miniconda3/envs/openrlhf/bin/deepspeed", line 6, in <module>
    main()
  File "/home/wdli/scratch/miniconda3/envs/openrlhf/lib/python3.11/site-packages/deepspeed/launcher/runner.py", line 426, in main
    active_resources = parse_inclusion_exclusion(resource_pool, args.include, args.exclude)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wdli/scratch/miniconda3/envs/openrlhf/lib/python3.11/site-packages/deepspeed/launcher/runner.py", line 350, in parse_inclusion_exclusion
    return parse_resource_filter(active_resources, include_str=inclusion, exclude_str=exclusion)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wdli/scratch/miniconda3/envs/openrlhf/lib/python3.11/site-packages/deepspeed/launcher/runner.py", line 295, in parse_resource_filter
    slots = [int(x) for x in slots.split(SLOT_SEP)]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wdli/scratch/miniconda3/envs/openrlhf/lib/python3.11/site-packages/deepspeed/launcher/runner.py", line 295, in <listcomp>
    slots = [int(x) for x in slots.split(SLOT_SEP)]
             ^^^^^^
ValueError: invalid literal for int() with base 10: 'MIG-cfb2a8ae-864b-50df-94a5-98983023f29d'
```
Thanks a lot!

**Comment by hijkzzz** [comment]
please use the docker container...
