### ISSUE TITLE
OOM with Llama3-8b on 8*H100 

### ISSUE THREAD

**Issue by sharptcode** [OpenRLHF/OpenRLHF#519]
I was running the example script: `examples/scripts/train_ppo_llama.sh`.
Basically, it's ppo on llama3-8b with 8*H100, flash_attn, zero3, gradient_checkpointing, adam_offload, but it's OOM after some training updates. Any suggestions would be appreciated!

### Command
```
set -x

read -r -d '' training_commands <<EOF
openrlhf.cli.train_ppo \
   --pretrain OpenRLHF/Llama-3-8b-sft-mixture \
   --reward_pretrain OpenRLHF/Llama-3-8b-rm-mixture \
   --save_path ./checkpoint/llama-3-8b-rlhf \
   --save_steps -1 \
   --logging_steps 1 \
   --eval_steps -1 \
   --micro_train_batch_size 2 \
   --train_batch_size 128 \
   --micro_rollout_batch_size 4 \
   --rollout_batch_size 1024 \
   --max_epochs 1 \
   --prompt_max_len 1024 \
   --generate_max_len 1024 \
   --zero_stage 2 \
   --bf16 \
   --actor_learning_rate 5e-7 \
   --critic_learning_rate 9e-6 \
   --init_kl_coef 0.01 \
   --prompt_data OpenRLHF/prompt-collection-v0.1 \
   --input_key context_messages \
   --apply_chat_template \
   --max_samples 100000 \
   --normalize_reward \
   --adam_offload \
   --flash_attn \
   --load_checkpoint \
   --gradient_checkpointing
EOF

    # --packing_samples
    # --use_wandb [WANDB_TOKENS] or True (use wandb login command)
    # --remote_rm_url http://localhost:5000/get_reward

if [[ ${1} != "slurm" ]]; then
    deepspeed --module $training_commands
fi
```

### Envs
Latest OpenRLHF (pip install -e .)
transformers==4.46.1
flash_attn==2.6.1
deepspeed==0.15.0
torch==2.3.1

### Hardware 
8*H100-80G
Memory: 1.8T

### Trace
```
make_experience: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 32/32 [00:21<00:00,  1.52it/s]
['user\nYou are given a math word problem and you are supposed to apply addition or subtraction mathematical operators on the numbers embedded in the text to answer the following question and then only report the final numerical answer.\n\n[Q]: Ronald has 13 blocks. Martha has with 4 blocks. Martha finds another 80. How many blocks does Martha end with?\n[A]: 84\n\n\n[Q]: While on vacation, Megan took 15 pictures at the zoo and 18 at the museum. If she later deleted 31 of the pictures, how many pictures from her vacation did she still have?\n[A]: 2\n\n\n[Q]: Allie counted the leftover ice cream after a sundae party. She had 0.3333333333333333 carton of rocky road ice cream, 0.3333333333333333 carton of cookie dough ice cream, and 0.16666666666666666 carton of strawberry cheesecake ice cream. How many cartons of ice cream did Allie have in all?\n[A]:\nassistant\n1']
Train epoch [1/1]: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 64/64 [03:53<00:00,  3.65s/it, pg=-0.0371, rm=0.583, ret=0.583, glen=197, tlen=510, kl=0, act_lr=1.67e-7, cri=0.0451, vals=0.718, cri_lr=3e-6]
make_experience: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 32/32 [00:18<00:00,  1.77it/s]
['user\nCan you write Python code to compute factorial without using recursion.\nassistant\nYes, I can help you with that. Here\'s a Python function to compute the factorial of a number without using recursion:\n\n```python\ndef factorial(n):\n    result = 1\n    for i in range(1, n + 1):\n        result *= i\n    return result\n\n# Example usage\nnumber = 5\nprint("Factorial of", number, "is", factorial(number))\n```\n\nThis function uses a for loop to calculate the factorial of the given number.\nuser\nThanks. Can you re-write this with recursion?\nassistant\nSure, here\'s the same function rewritten to use recursion:\n\n```python\ndef factorial(n):\n    if n == 1 or n == 0:\n        return 1\n    else:\n        return n * factorial(n - 1)\n\n# Example usage\nnumber = 5\nprint("Factorial of", number, "is", factorial(number))\n```\n\nThis function calculates the factorial of the given number by recursively multiplying the number with the factorial of the number minus one.\nuser\nCan you write a function that outputs the Fibonacci sequence without using recursion?\nassistant\nSure, here\'s a Python function to generate the Fibonacci sequence without using recursion:\n\n```python\ndef fibonacci(n):\n    seq = [0, 1]\n    for i in range(2, n):\n        seq.append(seq[i-1] + seq[i-2])\n    return seq\n```\n\nThis function initially sets the first two elements of the sequence to 0 and 1, then iterates from 2 to the given number, adding up the previous two elements to generate the next number in the sequence.\n\nTo generate a Fibonacci sequence with a specific number of elements, you can call this function with the desired number of elements. For example:\n\n```python\nnumber_of_elements = 10\nfib_seq = fibonacci(number_of_elements)\nprint(fib_seq)\n```\n\nThis will output the first 10 Fibonacci numbers: [0, 1, 1, 2, 3, 5, 8, 13, 21, 34].']
Train epoch [1/1]:  86%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                     | 55/64 [03:06<00:30,  3.40s/it, pg=0.00142, rm=0.65, ret=0.648, glen=219, tlen=570, kl=0.000625, act_lr=2.92e-7, cri=0.035, vals=0.718, cri_lr=5.25e-6]
[rank0]: Traceback (most recent call last):█████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                     | 55/64 [03:04<00:27,  3.10s/it, pg=0.00142, rm=0.65, ret=0.648, glen=219, tlen=570, kl=0.000625, act_lr=2.92e-7, cri=0.035, vals=0.718, cri_lr=5.25e-6]
[rank0]:   File "/export/home/global_conda/envs/openrlhf_11072024/lib/python3.10/runpy.py", line 196, in _run_module_as_main
[rank0]:     return _run_code(code, main_globals, None,
[rank0]:   File "/export/home/global_conda/envs/openrlhf_11072024/lib/python3.10/runpy.py", line 86, in _run_code
[rank0]:     exec(code, run_globals)
[rank0]:   File "/export/home/openrlhf_11072024/OpenRLHF/openrlhf/cli/train_ppo.py", line 434, in <module>
[rank0]:     train(args)
[rank0]:   File "/export/home/openrlhf_11072024/OpenRLHF/openrlhf/cli/train_ppo.py", line 268, in train
[rank0]:     trainer.fit(args, prompts_dataloader, pretrain_dataloader, consumed_samples, num_update_steps_per_episodes)
[rank0]:   File "/export/home/openrlhf_11072024/OpenRLHF/openrlhf/trainer/ppo_trainer.py", line 240, in fit
[rank0]:     status = self.ppo_train(steps)
[rank0]:   File "/export/home/openrlhf_11072024/OpenRLHF/openrlhf/trainer/ppo_trainer.py", line 282, in ppo_train
[rank0]:     status = self.training_step(experience, global_steps)
[rank0]:   File "/export/home/openrlhf_11072024/OpenRLHF/openrlhf/trainer/ppo_trainer.py", line 327, in training_step
[rank0]:     status = self.training_step_actor(experience)
[rank0]:   File "/export/home/openrlhf_11072024/OpenRLHF/openrlhf/trainer/ppo_trainer.py", line 375, in training_step_actor
[rank0]:     self.strategy.backward(loss, self.actor, self.actor_optim)
[rank0]:   File "/export/home/openrlhf_11072024/OpenRLHF/openrlhf/utils/deepspeed.py", line 129, in backward
[rank0]:     model.backward(loss)
[rank0]:   File "/export/home/global_conda/envs/openrlhf_11072024/lib/python3.10/site-packages/deepspeed/utils/nvtx.py", line 18, in wrapped_fn
[rank0]:     ret_val = func(*args, **kwargs)
[rank0]:   File "/export/home/global_conda/envs/openrlhf_11072024/lib/python3.10/site-packages/deepspeed/runtime/engine.py", line 2046, in backward
[rank0]:     self.allreduce_gradients()
[rank0]:   File "/export/home/global_conda/envs/openrlhf_11072024/lib/python3.10/site-packages/deepspeed/utils/nvtx.py", line 18, in wrapped_fn
[rank0]:     ret_val = func(*args, **kwargs)
[rank0]:   File "/export/home/global_conda/envs/openrlhf_11072024/lib/python3.10/site-packages/deepspeed/runtime/engine.py", line 1965, in allreduce_gradients
[rank0]:     self.optimizer.overlapping_partition_gradients_reduce_epilogue()
[rank0]:   File "/export/home/global_conda/envs/openrlhf_11072024/lib/python3.10/site-packages/deepspeed/runtime/zero/stage_1_and_2.py", line 868, in overlapping_partition_gradients_reduce_epilogue
[rank0]:     self.independent_gradient_partition_epilogue()
[rank0]:   File "/export/home/global_conda/envs/openrlhf_11072024/lib/python3.10/site-packages/deepspeed/runtime/zero/stage_1_and_2.py", line 759, in independent_gradient_partition_epilogue
[rank0]:     self.reduce_ipg_grads()
[rank0]:   File "/export/home/global_conda/envs/openrlhf_11072024/lib/python3.10/site-packages/deepspeed/runtime/zero/stage_1_and_2.py", line 1411, in reduce_ipg_grads
[rank0]:     self.copy_grads_in_partition(param)
[rank0]:   File "/export/home/global_conda/envs/openrlhf_11072024/lib/python3.10/site-packages/deepspeed/runtime/zero/stage_1_and_2.py", line 1335, in copy_grads_in_partition
[rank0]:     self.set_norm_for_param_grad_in_gpu(param)
[rank0]:   File "/export/home/global_conda/envs/openrlhf_11072024/lib/python3.10/site-packages/deepspeed/runtime/zero/stage_1_and_2.py", line 1265, in set_norm_for_param_grad_in_gpu
[rank0]:     self.norm_for_param_grads[param_id] = accumulated_grad.data.double().norm(2)
[rank0]: torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 3.91 GiB. GPU 
Episode [1/1]:   1%|█▏                                                                                                            | 1/97 [27:19<43:43:13, 1639.51s/it, policy_loss=0.0212, actor_lr=7.55e-8, kl=0, reward=0.497, response_length=225, total_length=535, return=0.497, critic_loss=0.0432, values=0.476, critic_lr=1.36e-6]
[2024-11-13 19:21:50,584] [INFO] [launch.py:319:sigkill_handler] Killing subprocess 1072203
[2024-11-13 19:21:50,584] [INFO] [launch.py:319:sigkill_handler] Killing subprocess 1072204
[2024-11-13 19:21:55,440] [INFO] [launch.py:319:sigkill_handler] Killing subprocess 1072205
[2024-11-13 19:21:59,817] [INFO] [launch.py:319:sigkill_handler] Killing subprocess 1072206
[2024-11-13 19:22:04,071] [INFO] [launch.py:319:sigkill_handler] Killing subprocess 1072207
[2024-11-13 19:22:08,404] [INFO] [launch.py:319:sigkill_handler] Killing subprocess 1072208
[2024-11-13 19:22:12,858] [INFO] [launch.py:319:sigkill_handler] Killing subprocess 1072209
[2024-11-13 19:22:17,272] [INFO] [launch.py:319:sigkill_handler] Killing subprocess 1072210
[2024-11-13 19:22:21,564] [ERROR] [launch.py:325:sigkill_handler] ['/export/home/global_conda/envs/openrlhf_11072024/bin/python', '-u', '-m', 'openrlhf.cli.train_ppo', '--local_rank=7', '--pretrain', 'OpenRLHF/Llama-3-8b-sft-mixture', '--reward_pretrain', 'OpenRLHF/Llama-3-8b-rm-mixture', '--save_path', './checkpoint/llama-3-8b-rlhf', '--save_steps', '-1', '--logging_steps', '1', '--eval_steps', '-1', '--micro_train_batch_size', '2', '--train_batch_size', '128', '--micro_rollout_batch_size', '4', '--rollout_batch_size', '1024', '--max_epochs', '1', '--prompt_max_len', '1024', '--generate_max_len', '1024', '--zero_stage', '2', '--bf16', '--actor_learning_rate', '5e-7', '--critic_learning_rate', '9e-6', '--init_kl_coef', '0.01', '--prompt_data', 'OpenRLHF/prompt-collection-v0.1', '--input_key', 'context_messages', '--apply_chat_template', '--max_samples', '100000', '--normalize_reward', '--adam_offload', '--flash_attn', '--load_checkpoint', '--gradient_checkpointing'] exits with return code = 1
```

**Comment by hijkzzz** [comment]
Please try train_ppo_ray.py
