### ISSUE TITLE
flash-attn无法正常工作

### ISSUE THREAD

**Issue by Shiroe7** [OpenRLHF/OpenRLHF#538]
### 现象描述
根据文档创建docker后pip install openrlhf 出现依赖报错
![image](https://github.com/user-attachments/assets/d3026783-4f40-442f-b7e2-816426326854)
使用git 仓库安装会出现一样的情况

随后会在运行时会发生错误：
![image](https://github.com/user-attachments/assets/ff7f4caf-02cc-42af-9ba4-32470f9ac4d5)

在不使用docker而是自己搭建conda环境时，会产生类似的运行报错：
![image](https://github.com/user-attachments/assets/3f8f2525-cfa4-4a8f-b5b6-7fab42e97159)
使用torch==2.4.1 torchvision==0.19.1 torchaudio==2.4.1时可以正常加载模型，但是推理时会报错：
![image](https://github.com/user-attachments/assets/5d476460-61d2-4070-a8ca-16c17ce73c12)
发生错误的cuda环境版本:
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2024 NVIDIA Corporation
Built on Thu_Mar_28_02:18:24_PDT_2024
Cuda compilation tools, release 12.4, V12.4.131
Build cuda_12.4.r12.4/compiler.34097967_0
docker 内cuda环境版本：
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2023 NVIDIA Corporation
Built on Wed_Nov_22_10:17:15_PST_2023
Cuda compilation tools, release 12.3, V12.3.107
Build cuda_12.3.r12.3/compiler.33567101_0
### 问题
这是否是cuda的兼容问题，还是在环境搭建过程中发生了错误

**Comment by hijkzzz** [comment]
container 里面要先删除自带的 flash_attn

**Comment by chuangzhidan** [comment]
[2024-12-23 10:54:26,589] [INFO] [real_accelerator.py:203:get_accelerator] Setting ds_accelerator to cuda (auto detect)
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/workspace/OpenRLHF/openrlhf/cli/train_dpo.py", line 9, in <module>
    from openrlhf.models import Actor
  File "/workspace/OpenRLHF/openrlhf/models/__init__.py", line 14, in <module>
    from .model import get_llm_for_sequence_regression
  File "/workspace/OpenRLHF/openrlhf/models/model.py", line 6, in <module>
    from flash_attn.utils.distributed import all_gather
  File "/usr/local/lib/python3.10/dist-packages/flash_attn/__init__.py", line 3, in <module>
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/workspace/OpenRLHF/openrlhf/cli/train_dpo.py", line 9, in <module>
    from openrlhf.models import Actor
  File "/workspace/OpenRLHF/openrlhf/models/__init__.py", line 14, in <module>
    from .model import get_llm_for_sequence_regression
  File "/workspace/OpenRLHF/openrlhf/models/model.py", line 6, in <module>
    from flash_attn.utils.distributed import all_gather
  File "/usr/local/lib/python3.10/dist-packages/flash_attn/__init__.py", line 3, in <module>
    from flash_attn.flash_attn_interface import (
  File "/usr/local/lib/python3.10/dist-packages/flash_attn/flash_attn_interface.py", line 10, in <module>
    from flash_attn.flash_attn_interface import (
  File "/usr/local/lib/python3.10/dist-packages/flash_attn/flash_attn_interface.py", line 10, in <module>
    import flash_attn_2_cuda as flash_attn_cuda
ImportError    : import flash_attn_2_cuda as flash_attn_cuda/usr/local/lib/python3.10/dist-packages/flash_attn_2_cuda.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZN3c105ErrorC2ENS_14SourceLocationENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE

ImportError: /usr/local/lib/python3.10/dist-packages/flash_attn_2_cuda.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZN3c105ErrorC2ENS_14SourceLocationENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE
[2024-12-23 10:54:30,514] [INFO] [launch.py:319:sigkill_handler] Killing subprocess 4716
[2024-12-23 10:54:30,514] [INFO] [launch.py:319:sigkill_handler] Killing subprocess 4717
[2024-12-23 10:54:30,517] [ERROR] [launch.py:325:sigkill_handler] ['/usr/bin/python', '-u', '-m', 'openrlhf.cli.train_dpo', '--local_rank=1', '--save_path', './checkpoint/Qwen2.5-0.5B-dpo', '--save_steps', '-1', '--logging_steps', '1', '--eval_steps', '-1', '--train_batch_size', '256', '--micro_train_batch_size', '1', '--pretrain', '/media/data/llm/Qwen2.5-0.5B-Instruct', '--bf16', '--max_epochs', '1', '--max_len', '8192', '--zero_stage', '3', '--learning_rate', '5e-7', '--beta', '0.1', '--dataset', 'OpenRLHF/preference_dataset_mixture2_and_safe_pku', '--apply_chat_template', '--chosen_key', 'chosen', '--rejected_key', 'rejected', '--flash_attn', '--gradient_checkpointing'] exits with return code = 1
root@e4b47fc2098b:/workspace/OpenRLHF# python -c "import torch; print(torch.__version__, torch.cuda.is_available(), torch.version.cuda)"
**2.5.1+cu124 True 12.4**
root@e4b47fc2098b:/workspace/OpenRLHF# nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2024 NVIDIA Corporation
Built on Thu_Jun__6_02:18:23_PDT_2024
Cuda compilation tools, release 12.5, V12.5.82
**Build cuda_12.5.r12.5/compiler.34385749_0**
root@e4b47fc2098b:/workspace/OpenRLHF# ^C
root@e4b47fc2098b:/workspace/OpenRLHF# pip show torch
Name: torch
**Version: 2.5.1**
Summary: Tensors and Dynamic neural networks in Python with strong GPU acceleration
Home-page: https://pytorch.org/
Author: PyTorch Team
Author-email: packages@pytorch.org
License: BSD-3-Clause
Location: /usr/local/lib/python3.10/d

same  flash_attn error ,is  flash_attn  really a must?

**Comment by chuangzhidan** [comment]
> container 里面要先删除自带的 flash_attn

讽刺的是，没有删除自带的 flash_attn，没有安装最新的版本，反而可以训练了

**Comment by NotTheStallion** [comment]
> [2024-12-23 10:54:26,589] [INFO] [real_accelerator.py:203:get_accelerator] Setting ds_accelerator to cuda (auto detect) Traceback (most recent call last): File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main return _run_code(code, main_globals, None, File "/usr/lib/python3.10/runpy.py", line 86, in _run_code exec(code, run_globals) File "/workspace/OpenRLHF/openrlhf/cli/train_dpo.py", line 9, in from openrlhf.models import Actor File "/workspace/OpenRLHF/openrlhf/models/**init**.py", line 14, in from .model import get_llm_for_sequence_regression File "/workspace/OpenRLHF/openrlhf/models/model.py", line 6, in from flash_attn.utils.distributed import all_gather File "/usr/local/lib/python3.10/dist-packages/flash_attn/**init**.py", line 3, in Traceback (most recent call last): File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main return _run_code(code, main_globals, None, File "/usr/lib/python3.10/runpy.py", line 86, in _run_code exec(code, run_globals) File "/workspace/OpenRLHF/openrlhf/cli/train_dpo.py", line 9, in from openrlhf.models import Actor File "/workspace/OpenRLHF/openrlhf/models/**init**.py", line 14, in from .model import get_llm_for_sequence_regression File "/workspace/OpenRLHF/openrlhf/models/model.py", line 6, in from flash_attn.utils.distributed import all_gather File "/usr/local/lib/python3.10/dist-packages/flash_attn/**init**.py", line 3, in from flash_attn.flash_attn_interface import ( File "/usr/local/lib/python3.10/dist-packages/flash_attn/flash_attn_interface.py", line 10, in from flash_attn.flash_attn_interface import ( File "/usr/local/lib/python3.10/dist-packages/flash_attn/flash_attn_interface.py", line 10, in import flash_attn_2_cuda as flash_attn_cuda **ImportError : import flash_attn_2_cuda as flash_attn_cuda/usr/local/lib/python3.10/dist-packages/flash_attn_2_cuda.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZN3c105ErrorC2ENS_14SourceLocationENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE**
> 
> **ImportError: /usr/local/lib/python3.10/dist-packages/flash_attn_2_cuda.cpython-310-x86_64-linux-gnu.so: undefined** symbol: _ZN3c105ErrorC2ENS_14SourceLocationENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE [2024-12-23 10:54:30,514] [INFO] [launch.py:319:sigkill_handler] Killing subprocess 4716 [2024-12-23 10:54:30,514] [INFO] [launch.py:319:sigkill_handler] Killing subprocess 4717 [2024-12-23 10:54:30,517] [ERROR] [launch.py:325:sigkill_handler] ['/usr/bin/python', '-u', '-m', 'openrlhf.cli.train_dpo', '--local_rank=1', '--save_path', './checkpoint/Qwen2.5-0.5B-dpo', '--save_steps', '-1', '--logging_steps', '1', '--eval_steps', '-1', '--train_batch_size', '256', '--micro_train_batch_size', '1', '--pretrain', '/media/data/llm/Qwen2.5-0.5B-Instruct', '--bf16', '--max_epochs', '1', '--max_len', '8192', '--zero_stage', '3', '--learning_rate', '5e-7', '--beta', '0.1', '--dataset', 'OpenRLHF/preference_dataset_mixture2_and_safe_pku', '--apply_chat_template', '--chosen_key', 'chosen', '--rejected_key', 'rejected', '--flash_attn', '--gradient_checkpointing'] exits with return code = 1 root@e4b47fc2098b:/workspace/OpenRLHF# python -c "import torch; print(torch.**version**, torch.cuda.is_available(), torch.version.cuda)" **2.5.1+cu124 True 12.4** root@e4b47fc2098b:/workspace/OpenRLHF# nvcc --version nvcc: NVIDIA (R) Cuda compiler driver Copyright (c) 2005-2024 NVIDIA Corporation Built on Thu_Jun__6_02:18:23_PDT_2024 Cuda compilation tools, release 12.5, V12.5.82 **Build cuda_12.5.r12.5/compiler.34385749_0** root@e4b47fc2098b:/workspace/OpenRLHF# ^C root@e4b47fc2098b:/workspace/OpenRLHF# pip show torch Name: torch **Version: 2.5.1** Summary: Tensors and Dynamic neural networks in Python with strong GPU acceleration Home-page: https://pytorch.org/ Author: PyTorch Team Author-email: [packages@pytorch.org](mailto:packages@pytorch.org) License: BSD-3-Clause Location: /usr/local/lib/python3.10/d
> 
> **same flash_attn error ,is flash_attn really a must?? beacuase it's really upsetting**
> 
> flash_attn-2.7.1.post4+cu12torch2.5cxx11abiTRUE-cp310-cp310-linux_x86_64.whl this one doesn't work either

I have the same problem and i have no idea how to solve it. I used different versions of flash-attn and pytorch but in vain.

**Comment by Rinstein** [comment]
same problem:
```
  File "/usr/local/lib/python3.10/dist-packages/transformers/utils/import_utils.py", line 1969, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import transformers.models.bloom.modeling_bloom because of the following error (look up to see its traceback):
/usr/local/lib/python3.10/dist-packages/flash_attn_2_cuda.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZN3c105ErrorC2ENS_14SourceLocationENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE

---------------------------------------
Job 'raysubmit_xP3YPg32RiUrtjKp' failed
---------------------------------------

Status message: Job entrypoint command failed with exit code 1, last available logs (truncated to 20,000 chars):
    from transformers import BloomPreTrainedModel
  File "<frozen importlib._bootstrap>", line 1075, in _handle_fromlist
  File "/usr/local/lib/python3.10/dist-packages/transformers/utils/import_utils.py", line 1956, in __getattr__
    value = getattr(module, name)
  File "/usr/local/lib/python3.10/dist-packages/transformers/utils/import_utils.py", line 1955, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "/usr/local/lib/python3.10/dist-packages/transformers/utils/import_utils.py", line 1969, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import transformers.models.bloom.modeling_bloom because of the following error (look up to see its traceback):
/usr/local/lib/python3.10/dist-packages/flash_attn_2_cuda.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZN3c105ErrorC2ENS_14SourceLocationENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE
```
Do you find fix way? @NotTheStallion

**Comment by lixali** [comment]
I have the same problem. How to resolve it?

**Comment by lixali** [comment]
> > [2024-12-23 10:54:26,589] [INFO] [real_accelerator.py:203:get_accelerator] Setting ds_accelerator to cuda (auto detect) Traceback (most recent call last): File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main return _run_code(code, main_globals, None, File "/usr/lib/python3.10/runpy.py", line 86, in _run_code exec(code, run_globals) File "/workspace/OpenRLHF/openrlhf/cli/train_dpo.py", line 9, in from openrlhf.models import Actor File "/workspace/OpenRLHF/openrlhf/models/**init**.py", line 14, in from .model import get_llm_for_sequence_regression File "/workspace/OpenRLHF/openrlhf/models/model.py", line 6, in from flash_attn.utils.distributed import all_gather File "/usr/local/lib/python3.10/dist-packages/flash_attn/**init**.py", line 3, in Traceback (most recent call last): File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main return _run_code(code, main_globals, None, File "/usr/lib/python3.10/runpy.py", line 86, in _run_code exec(code, run_globals) File "/workspace/OpenRLHF/openrlhf/cli/train_dpo.py", line 9, in from openrlhf.models import Actor File "/workspace/OpenRLHF/openrlhf/models/**init**.py", line 14, in from .model import get_llm_for_sequence_regression File "/workspace/OpenRLHF/openrlhf/models/model.py", line 6, in from flash_attn.utils.distributed import all_gather File "/usr/local/lib/python3.10/dist-packages/flash_attn/**init**.py", line 3, in from flash_attn.flash_attn_interface import ( File "/usr/local/lib/python3.10/dist-packages/flash_attn/flash_attn_interface.py", line 10, in from flash_attn.flash_attn_interface import ( File "/usr/local/lib/python3.10/dist-packages/flash_attn/flash_attn_interface.py", line 10, in import flash_attn_2_cuda as flash_attn_cuda **ImportError : import flash_attn_2_cuda as flash_attn_cuda/usr/local/lib/python3.10/dist-packages/flash_attn_2_cuda.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZN3c105ErrorC2ENS_14SourceLocationENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE**
> > **ImportError: /usr/local/lib/python3.10/dist-packages/flash_attn_2_cuda.cpython-310-x86_64-linux-gnu.so: undefined** symbol: _ZN3c105ErrorC2ENS_14SourceLocationENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE [2024-12-23 10:54:30,514] [INFO] [launch.py:319:sigkill_handler] Killing subprocess 4716 [2024-12-23 10:54:30,514] [INFO] [launch.py:319:sigkill_handler] Killing subprocess 4717 [2024-12-23 10:54:30,517] [ERROR] [launch.py:325:sigkill_handler] ['/usr/bin/python', '-u', '-m', 'openrlhf.cli.train_dpo', '--local_rank=1', '--save_path', './checkpoint/Qwen2.5-0.5B-dpo', '--save_steps', '-1', '--logging_steps', '1', '--eval_steps', '-1', '--train_batch_size', '256', '--micro_train_batch_size', '1', '--pretrain', '/media/data/llm/Qwen2.5-0.5B-Instruct', '--bf16', '--max_epochs', '1', '--max_len', '8192', '--zero_stage', '3', '--learning_rate', '5e-7', '--beta', '0.1', '--dataset', 'OpenRLHF/preference_dataset_mixture2_and_safe_pku', '--apply_chat_template', '--chosen_key', 'chosen', '--rejected_key', 'rejected', '--flash_attn', '--gradient_checkpointing'] exits with return code = 1 root@e4b47fc2098b:/workspace/OpenRLHF# python -c "import torch; print(torch.**version**, torch.cuda.is_available(), torch.version.cuda)" **2.5.1+cu124 True 12.4** root@e4b47fc2098b:/workspace/OpenRLHF# nvcc --version nvcc: NVIDIA (R) Cuda compiler driver Copyright (c) 2005-2024 NVIDIA Corporation Built on Thu_Jun__6_02:18:23_PDT_2024 Cuda compilation tools, release 12.5, V12.5.82 **Build cuda_12.5.r12.5/compiler.34385749_0** root@e4b47fc2098b:/workspace/OpenRLHF# ^C root@e4b47fc2098b:/workspace/OpenRLHF# pip show torch Name: torch **Version: 2.5.1** Summary: Tensors and Dynamic neural networks in Python with strong GPU acceleration Home-page: https://pytorch.org/ Author: PyTorch Team Author-email: [packages@pytorch.org](mailto:packages@pytorch.org) License: BSD-3-Clause Location: /usr/local/lib/python3.10/d
> > **same flash_attn error ,is flash_attn really a must?? beacuase it's really upsetting**
> > flash_attn-2.7.1.post4+cu12torch2.5cxx11abiTRUE-cp310-cp310-linux_x86_64.whl this one doesn't work either
> 
> I have the same problem and i have no idea how to solve it. I used different versions of flash-attn and pytorch but in vain.

Just wonder have you resolved it? I have the exact same error.

**Comment by NotTheStallion** [comment]
I forgot to write a follow-up or the temporary fix I found.
I removed the use of Flash-attn, it has been some time but i think i ended up removing parts of the code that import flash -attn and i didn't install as it broke my entire build wheel.

I hope you find this usefull.

**Comment by lixali** [comment]
> I forgot to write a follow-up or the temporary fix I found. I removed the use of Flash-attn, it has been some time but i think i ended up removing parts of the code that import flash -attn and i didn't install as it broke my entire build wheel.
> 
> I hope you find this usefull.

Thank you. It is good to know that it works after removing flash attention. Flash attention is a pain to install the right version and debug. 

Can I quickly ask at the end, you have it running and training PPO without any issue and wonder if your project open sourced (be checked in GitHub somewhere) and I can run and try out your run to do PPO? 

Thank you!!

**Comment by NotTheStallion** [comment]
The goal of my work was to understand how PPO works by switching OpenRLHF to work on a single node. 
I got it working at some point but i didn't save it.

Try to remove all self-attn imports and it should normaly work.
