### ISSUE TITLE
Gradient accumulation steps: {grad_acc} has to be greater than 0

### ISSUE THREAD

**Issue by lxnlxnlxnlxnlxn** [OpenRLHF/OpenRLHF#584]
您好，我用8张40GB的A800跑llama2-7b模型，出现以下问题
```
[rank4]: Traceback (most recent call last):
[rank4]:   File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
[rank4]:     return _run_code(code, main_globals, None,
[rank4]:   File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
[rank4]:     exec(code, run_globals)
[rank4]:   File "/workspace/OpenRLHF/openrlhf/cli/train_ppo.py", line 417, in <module>
[rank4]:     train(args)
[rank4]:   File "/workspace/OpenRLHF/openrlhf/cli/train_ppo.py", line 199, in train
[rank4]:     ) = strategy.prepare(
[rank4]:   File "/workspace/OpenRLHF/openrlhf/utils/deepspeed.py", line 193, in prepare
[rank4]:     ret.append(self._ds_init_train_model(*arg))
[rank4]:   File "/workspace/OpenRLHF/openrlhf/utils/deepspeed.py", line 203, in _ds_init_train_model
[rank4]:     engine, optim, _, scheduler = deepspeed.initialize(
[rank4]:   File "/usr/local/lib/python3.10/dist-packages/deepspeed/__init__.py", line 179, in initialize
[rank4]:     config_class = DeepSpeedConfig(config, mpu, mesh_device=mesh_device)
[rank4]:   File "/usr/local/lib/python3.10/dist-packages/deepspeed/runtime/config.py", line 798, in __init__
[rank4]:     self._configure_train_batch_size()
[rank4]:   File "/usr/local/lib/python3.10/dist-packages/deepspeed/runtime/config.py", line 981, in _configure_train_batch_size
[rank4]:     self._batch_assertion()
[rank4]:   File "/usr/local/lib/python3.10/dist-packages/deepspeed/runtime/config.py", line 927, in _batch_assertion
[rank4]:     assert (grad_acc > 0), f"Gradient accumulation steps: {grad_acc} has to be greater than 0"
[rank4]: AssertionError: Gradient accumulation steps: 0 has to be greater than 0
```
运行参数如下：
```
openrlhf.cli.train_ppo \
   --pretrain /data/Llama-2-7b-chat-hf \
   --reward_pretrain /data/Llama-2-7b-chat-hf \
   --save_path /workspace/checkpoint/Llama-2-7b-chat-hf \
   --save_steps -1 \
   --logging_steps 1 \
   --eval_steps -1 \
   --micro_train_batch_size 2 \
   --train_batch_size 8 \
   --micro_rollout_batch_size 4 \
   --rollout_batch_size 16 \
   --max_epochs 1 \
   --prompt_max_len 128 \
   --generate_max_len 128 \
   --zero_stage 2 \
   --bf16 \
   --actor_learning_rate 5e-7 \
   --critic_learning_rate 9e-6 \
   --init_kl_coef 0.01 \
   --prompt_data /data/dataset/Dahoas--rm-static \
   --input_key prompt \
   --max_samples 1000 \
   --normalize_reward \
   --adam_offload \
   --load_checkpoint \
   --gradient_checkpointing
```

**Comment by hijkzzz** [comment]
我估计是 batch size 太小了 多卡不够分

**Comment by Takeru0618** [comment]
我也出现了同样的问题，而且我的batch_size 一到16，就outofmemory了，我的是4090，Llama3-8b

**Comment by thelongestusernameofall** [comment]
注意 train_batch、micro_batch和gradient_accumulation_steps关系如下。
   grad_acc = train_batch // micro_batch
   grad_acc //= self.world_size
   self.gradient_accumulation_steps = grad_acc

确保grad_acc不为0即可。

**Comment by zia1138** [comment]
I noticed that this grad_acc > 0 error occurs if  args.micro_train_batch_size  !=  args.actor_num_gpus_per_node *  args.train_batch_size. I think it has to do with the fact that deepspeed has some logic around gradient_accumulation_steps  https://www.deepspeed.ai/docs/config-json/ when it's not provided.
