### ISSUE TITLE
Ray env reports a circular import

### ISSUE THREAD

**Issue by ToheartZhang** [OpenRLHF/OpenRLHF#603]
Command:
```
source /share/project/zhipengchen/chenjie/eval_env/bin/activate

# cd /share/project/zhipengchen/zbc/JiuZhang3.0/OpenRLHF

# launch the master node of ray in container
# ray start --head --node-ip-address 0.0.0.0 --num-gpus 8

# if you want to launch ray on more nodes, use
# ray start --address {MASTER-NODE-ADDRESS}:6379  --num-gpus 8

ray job submit --address="http://127.0.0.1:8265" \
   --runtime-env-json='{"working_dir": "/path/to/openrlhf"}' \
   -- python3 -m openrlhf.cli.train_ppo_ray \
   --ref_num_nodes 1 \
   --ref_num_gpus_per_node 2 \
   --reward_num_nodes 1 \
   --reward_num_gpus_per_node 2 \
   --critic_num_nodes 1 \
   --critic_num_gpus_per_node 2 \
   --actor_num_nodes 1 \
   --actor_num_gpus_per_node 2 \
   --vllm_num_engines 2 \
   --vllm_tensor_parallel_size 2 \
   --colocate_critic_reward \
   --colocate_actor_ref \
   --pretrain /share/project/zhipengchen/model/Llama-3-8b-sft-mixture \
   --reward_pretrain /share/project/zhipengchen/model/Llama-3-8b-rm-mixture \
   --save_path /share/project/zhipengchen/zbc/results/llama-3-8b-rlhf \
   --micro_train_batch_size 8 \
   --train_batch_size 128 \
   --micro_rollout_batch_size 32 \
   --rollout_batch_size 1024 \
   --max_samples 100000 \
   --max_epochs 1 \
   --prompt_max_len 1024 \
   --generate_max_len 1024 \
   --zero_stage 3 \
   --bf16 \
   --actor_learning_rate 5e-7 \
   --critic_learning_rate 9e-6 \
   --init_kl_coef 0.01 \
   --prompt_data /share/project/zhipengchen/chenjie/RLHF/dataset/prompt-collection-v0.1 \
   --input_key context_messages \
   --apply_chat_template \
   --packing_samples \
   --normalize_reward \
   --adam_offload \
   --flash_attn \
   --gradient_checkpointing \
```

Log:
```
nohup: ignoring input
2024-12-19 12:45:03,137 INFO cli.py:39 -- [37mJob submission server address[39m: [1mhttp://127.0.0.1:8265[22m
2024-12-19 12:45:03,157 INFO dashboard_sdk.py:385 -- Package gcs://_ray_pkg_3bf242eb12db0e64.zip already exists, skipping upload.
2024-12-19 12:45:03,165 SUCC cli.py:63 -- [32m-------------------------------------------------------[39m
2024-12-19 12:45:03,166 SUCC cli.py:64 -- [32mJob 'raysubmit_SpCk9PkU1tN3hUzT' submitted successfully[39m
2024-12-19 12:45:03,166 SUCC cli.py:65 -- [32m-------------------------------------------------------[39m
2024-12-19 12:45:03,166 INFO cli.py:289 -- [36mNext steps[39m
2024-12-19 12:45:03,166 INFO cli.py:290 -- Query the logs of the job:
2024-12-19 12:45:03,166 INFO cli.py:292 -- [1mray job logs raysubmit_SpCk9PkU1tN3hUzT[22m
2024-12-19 12:45:03,166 INFO cli.py:294 -- Query the status of the job:
2024-12-19 12:45:03,166 INFO cli.py:296 -- [1mray job status raysubmit_SpCk9PkU1tN3hUzT[22m
2024-12-19 12:45:03,166 INFO cli.py:298 -- Request the job to be stopped:
2024-12-19 12:45:03,166 INFO cli.py:300 -- [1mray job stop raysubmit_SpCk9PkU1tN3hUzT[22m
2024-12-19 12:45:03,168 INFO cli.py:307 -- Tailing logs until the job exits (disable with --no-wait):
2024-12-19 12:45:03,162 INFO job_manager.py:530 -- Runtime env is setting up.
[2024-12-19 12:45:11,409] [INFO] [real_accelerator.py:203:get_accelerator] Setting ds_accelerator to cuda (auto detect)
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/share/project/zhipengchen/chenjie/eval_env/lib/python3.10/site-packages/openrlhf/cli/train_ppo_ray.py", line 9, in <module>
    from openrlhf.trainer.ray import (
  File "/share/project/zhipengchen/chenjie/eval_env/lib/python3.10/site-packages/openrlhf/trainer/__init__.py", line 1, in <module>
    from .dpo_trainer import DPOTrainer
  File "/share/project/zhipengchen/chenjie/eval_env/lib/python3.10/site-packages/openrlhf/trainer/dpo_trainer.py", line 10, in <module>
    from openrlhf.models import DPOLoss
  File "/share/project/zhipengchen/chenjie/eval_env/lib/python3.10/site-packages/openrlhf/models/__init__.py", line 14, in <module>
    from .model import get_llm_for_sequence_regression
  File "/share/project/zhipengchen/chenjie/eval_env/lib/python3.10/site-packages/openrlhf/models/model.py", line 12, in <module>
    from openrlhf.utils.logging_utils import init_logger
  File "/share/project/zhipengchen/chenjie/eval_env/lib/python3.10/site-packages/openrlhf/utils/__init__.py", line 2, in <module>
    from .utils import blending_datasets, get_strategy, get_tokenizer
  File "/share/project/zhipengchen/chenjie/eval_env/lib/python3.10/site-packages/openrlhf/utils/utils.py", line 3, in <module>
    from datasets import interleave_datasets, load_dataset, load_from_disk
  File "/tmp/ray/session_2024-12-19_12-02-10_977021_1391157/runtime_resources/working_dir_files/_ray_pkg_3bf242eb12db0e64/datasets/__init__.py", line 1, in <module>
    from .process_reward_dataset import ProcessRewardDataset
  File "/tmp/ray/session_2024-12-19_12-02-10_977021_1391157/runtime_resources/working_dir_files/_ray_pkg_3bf242eb12db0e64/datasets/process_reward_dataset.py", line 8, in <module>
    from openrlhf.utils.utils import convert_token_to_id
ImportError: cannot import name 'convert_token_to_id' from partially initialized module 'openrlhf.utils.utils' (most likely due to a circular import) (/share/project/zhipengchen/chenjie/eval_env/lib/python3.10/site-packages/openrlhf/utils/utils.py)
2024-12-19 12:45:17,195 ERR cli.py:71 -- [31m---------------------------------------[39m
2024-12-19 12:45:17,196 ERR cli.py:72 -- [31mJob 'raysubmit_SpCk9PkU1tN3hUzT' failed[39m
2024-12-19 12:45:17,196 ERR cli.py:73 -- [31m---------------------------------------[39m
2024-12-19 12:45:17,196 INFO cli.py:86 -- Status message: Job entrypoint command failed with exit code 1, last available logs (truncated to 20,000 chars):
    from openrlhf.utils.logging_utils import init_logger
  File "/share/project/zhipengchen/chenjie/eval_env/lib/python3.10/site-packages/openrlhf/utils/__init__.py", line 2, in <module>
    from .utils import blending_datasets, get_strategy, get_tokenizer
  File "/share/project/zhipengchen/chenjie/eval_env/lib/python3.10/site-packages/openrlhf/utils/utils.py", line 3, in <module>
    from datasets import interleave_datasets, load_dataset, load_from_disk
  File "/tmp/ray/session_2024-12-19_12-02-10_977021_1391157/runtime_resources/working_dir_files/_ray_pkg_3bf242eb12db0e64/datasets/__init__.py", line 1, in <module>
    from .process_reward_dataset import ProcessRewardDataset
  File "/tmp/ray/session_2024-12-19_12-02-10_977021_1391157/runtime_resources/working_dir_files/_ray_pkg_3bf242eb12db0e64/datasets/process_reward_dataset.py", line 8, in <module>
    from openrlhf.utils.utils import convert_token_to_id
ImportError: cannot import name 'convert_token_to_id' from partially initialized module 'openrlhf.utils.utils' (most likely due to a circular import) (/share/project/zhipengchen/chenjie/eval_env/lib/python3.10/site-packages/openrlhf/utils/utils.py)
```
 Is there an issue for setting working_dir? I tried to set it to a cloned project `OpenRLHF/openrlhf` or the `openrlhf` in the Python venv. Both report the same error. Is there anything I missed? Thanks in advance!

**Comment by hijkzzz** [comment]
pip install openrlhf?

**Comment by hwk0707** [comment]
It works for me that rename the datasets in this module into customer_datasets

**Comment by ToheartZhang** [comment]
I've fixed it by not setting working_dir, thx a lot!
