### ISSUE TITLE
The server socket has failed to bind to [::]:29500, deepspeed 端口被占用，使用的是8张H100，切换deepspeed 端口同样会有占用

### ISSUE THREAD

**Issue by Anlysqx** [OpenRLHF/OpenRLHF#618]
Traceback (most recent call last):
  File "/home/tiger/anaconda3/envs/openrlhf/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/tiger/anaconda3/envs/openrlhf/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/opt/tiger/openRLHF/OpenRLHF/openrlhf/cli/train_sft.py", line 252, in <module>
    train(args)
  File "/opt/tiger/openRLHF/OpenRLHF/openrlhf/cli/train_sft.py", line 20, in train
    strategy.setup_distributed()
  File "/opt/tiger/openRLHF/OpenRLHF/openrlhf/utils/deepspeed/deepspeed.py", line 83, in setup_distributed
    deepspeed.init_distributed(timeout=timeout)
  File "/home/tiger/anaconda3/envs/openrlhf/lib/python3.10/site-packages/deepspeed/comm/comm.py", line 685, in init_distributed
    cdb = TorchBackend(dist_backend, timeout, init_method, rank, world_size)
  File "/home/tiger/anaconda3/envs/openrlhf/lib/python3.10/site-packages/deepspeed/comm/torch.py", line 112, in __init__
    self.init_process_group(backend, timeout, init_method, rank, world_size)
  File "/home/tiger/anaconda3/envs/openrlhf/lib/python3.10/site-packages/deepspeed/comm/torch.py", line 142, in init_process_group
    torch.distributed.init_process_group(backend,
  File "/home/tiger/anaconda3/envs/openrlhf/lib/python3.10/site-packages/torch/distributed/c10d_logger.py", line 74, in wrapper
    func_return = func(*args, **kwargs)
  File "/home/tiger/anaconda3/envs/openrlhf/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 1141, in init_process_group
    store, rank, world_size = next(rendezvous_iterator)
  File "/home/tiger/anaconda3/envs/openrlhf/lib/python3.10/site-packages/torch/distributed/rendezvous.py", line 241, in _env_rendezvous_handler
    store = _create_c10d_store(master_addr, master_port, rank, world_size, timeout)
  File "/home/tiger/anaconda3/envs/openrlhf/lib/python3.10/site-packages/torch/distributed/rendezvous.py", line 172, in _create_c10d_store
    return TCPStore(
RuntimeError: The server socket has failed to listen on any local network address. The server socket has failed to bind to [::]:29500 (errno: 98 - Address already in use). The server socket has failed to bind to 0.0.0.0:29500 (errno: 98 - Address already in use).

训练配置使用的是：
![image](https://github.com/user-attachments/assets/40fae24c-e79c-40d6-a877-c0b7ca5d3b1c)

**Comment by Anlysqx** [comment]
done

**Comment by gongel** [comment]
@Anlysqx 你好，请问怎么解决的呢

**Comment by ywb2018** [comment]
@Anlysqx 同问怎么解决的

**Comment by AiteYx** [comment]
deepspeed --master_port=29501  ***
