### ISSUE TITLE
ValueError: not enough values to unpack (expected 8, got 0)

### ISSUE THREAD

**Issue by chuangzhidan** [OpenRLHF/OpenRLHF#619]
[2024-12-24 05:18:46,297] [INFO] [config.py:1003:print]   zero_optimization_stage ...... 0
[2024-12-24 05:18:46,297] [INFO] [config.py:989:print_user_config]   json = {
    "steps_per_print": 100, 
    "zero_optimization": {
        "stage": 0, 
        "stage3_param_persistence_threshold": "auto", 
        "offload_param": {
            "device": "none", 
            "pin_memory": true
        }
    }, 
    "bf16": {
        "enabled": true
    }, 
    "gradient_clipping": 1.0, 
    "prescale_gradients": false, 
    "wall_clock_breakdown": false, 
    "train_micro_batch_size_per_gpu": 1, 
    "train_batch_size": 256
}
Train epoch:   0%|                                                                                                                                                                                  | 0/1 [00:00<?, ?it/s[rank0]: Traceback (most recent call last):                                                                                                                                                     | 0/277451 [00:00<?, ?it/s]
[rank0]:   File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
[rank0]:     return _run_code(code, main_globals, None,
[rank0]:   File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
[rank0]:     exec(code, run_globals)
[rank0]:   File "/workspace/OpenRLHF/openrlhf/cli/train_dpo.py", line 274, in <module>
[rank0]:     train(args)
[rank0]:   File "/workspace/OpenRLHF/openrlhf/cli/train_dpo.py", line 149, in train
[rank0]:     trainer.fit(args, consumed_samples, num_update_steps_per_epoch)
[rank0]:   File "/workspace/OpenRLHF/openrlhf/trainer/dpo_trainer.py", line 176, in fit
[rank0]:     self.strategy.backward(loss, self.model, self.optimizer)
[rank0]:   File "/workspace/OpenRLHF/openrlhf/utils/deepspeed/deepspeed.py", line 129, in backward
[rank0]:     model.backward(loss)
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/deepspeed/utils/nvtx.py", line 18, in wrapped_fn
[rank0]:     ret_val = func(*args, **kwargs)
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/deepspeed/runtime/engine.py", line 2020, in backward
[rank0]:     self.optimizer.backward(loss, retain_graph=retain_graph)
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/deepspeed/runtime/zero/stage_1_and_2.py", line 2064, in backward
[rank0]:     self.loss_scaler.backward(loss.float(), retain_graph=retain_graph)
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/deepspeed/runtime/fp16/loss_scaler.py", line 63, in backward
[rank0]:     scaled_loss.backward(retain_graph=retain_graph)
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/torch/_tensor.py", line 581, in backward
[rank0]:     torch.autograd.backward(
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/torch/autograd/__init__.py", line 347, in backward
[rank0]:     _engine_run_backward(
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/torch/autograd/graph.py", line 825, in _engine_run_backward
[rank0]:     return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/torch/autograd/function.py", line 307, in apply
[rank0]:     return user_fn(self, *args)
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/flash_attn-2.7.2.post1-py3.10-linux-x86_64.egg/flash_attn/flash_attn_interface.py", line 957, in backward
[rank0]:     q, k, v, out, softmax_lse, cu_seqlens_q, cu_seqlens_k, rng_state = ctx.saved_tensors
[rank0]: ValueError: not enough values to unpack (expected 8, got 0)
Train epoch:   0%|                                                                                                                                                                                  | 0/1 [00:01<?, ?it/s]
Train step of epoch 0:   0%|                                                                                                                                                                   | 0/277451 [00:01<?, ?it/s]
[rank1]: Traceback (most recent call last):
[rank1]:   File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
[rank1]:     return _run_code(code, main_globals, None,
[rank1]:   File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
[rank1]:     exec(code, run_globals)
[rank1]:   File "/workspace/OpenRLHF/openrlhf/cli/train_dpo.py", line 274, in <module>
[rank1]:     train(args)
[rank1]:   File "/workspace/OpenRLHF/openrlhf/cli/train_dpo.py", line 149, in train
[rank1]:     trainer.fit(args, consumed_samples, num_update_steps_per_epoch)
[rank1]:   File "/workspace/OpenRLHF/openrlhf/trainer/dpo_trainer.py", line 176, in fit
[rank1]:     self.strategy.backward(loss, self.model, self.optimizer)
[rank1]:   File "/workspace/OpenRLHF/openrlhf/utils/deepspeed/deepspeed.py", line 129, in backward
[rank1]:     model.backward(loss)
[rank1]:   File "/usr/local/lib/python3.10/dist-packages/deepspeed/utils/nvtx.py", line 18, in wrapped_fn
[rank1]:     ret_val = func(*args, **kwargs)
[rank1]:   File "/usr/local/lib/python3.10/dist-packages/deepspeed/runtime/engine.py", line 2020, in backward
[rank1]:     self.optimizer.backward(loss, retain_graph=retain_graph)
[rank1]:   File "/usr/local/lib/python3.10/dist-packages/deepspeed/runtime/zero/stage_1_and_2.py", line 2064, in backward
[rank1]:     self.loss_scaler.backward(loss.float(), retain_graph=retain_graph)
[rank1]:   File "/usr/local/lib/python3.10/dist-packages/deepspeed/runtime/fp16/loss_scaler.py", line 63, in backward
[rank1]:     scaled_loss.backward(retain_graph=retain_graph)
[rank1]:   File "/usr/local/lib/python3.10/dist-packages/torch/_tensor.py", line 581, in backward
[rank1]:     torch.autograd.backward(
[rank1]:   File "/usr/local/lib/python3.10/dist-packages/torch/autograd/__init__.py", line 347, in backward
[rank1]:     _engine_run_backward(
[rank1]:   File "/usr/local/lib/python3.10/dist-packages/torch/autograd/graph.py", line 825, in _engine_run_backward
[rank1]:     return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
[rank1]:   File "/usr/local/lib/python3.10/dist-packages/torch/autograd/function.py", line 307, in apply
[rank1]:     return user_fn(self, *args)
**[rank1]:   File "/usr/local/lib/python3.10/dist-packages/flash_attn-2.7.2.post1-py3.10-linux-x86_64.egg/flash_attn/flash_attn_interface.py", line 957, in backward
[rank1]:     q, k, v, out, softmax_lse, cu_seqlens_q, cu_seqlens_k, rng_state = ctx.saved_tensors
[rank1]: ValueError: not enough values to unpack (expected 8, got 0)**
[rank0]:[W1224 05:18:49.339004811 ProcessGroupNCCL.cpp:1250] Warning: WARNING: process group has NOT been destroyed before we destruct ProcessGroupNCCL. On normal program exit, the application should call destroy_process_group to ensure that any pending NCCL operations have finished in this process. In rare cases this process can exit before this point and block the progress of another member of the process group. This constraint has always been present,  but this warning has only been added since PyTorch 2.4 (function operator())
[2024-12-24 05:18:51,254] [INFO] [launch.py:319:sigkill_handler] Killing subprocess 28418
[2024-12-24 05:18:51,255] [INFO] [launch.py:319:sigkill_handler] Killing subprocess 28419
[2024-12-24 05:18:53,131] [ERROR] [launch.py:325:sigkill_handler] ['/usr/bin/python', '-u', '-m', 'openrlhf.cli.train_dpo', '--local_rank=1', '--save_path', './checkpoint/Qwen2.5-0.5B-dpo', '--save_steps', '-1', '--logging_steps', '1', '--eval_steps', '-1', '--train_batch_size', '256', '--micro_train_batch_size', '1', '--pretrain', **'./model/Qwen2.5-0.5B-Instruct'**, '--bf16', '--max_epochs', '1', '--max_len', '8192', '--zero_stage', '3', '--learning_rate', '5e-7', '--beta', '0.1', '--dataset', 'OpenRLHF/preference_dataset_mixture2_and_safe_pku', '--apply_chat_template', '--chosen_key', 'chosen', '--rejected_key', 'rejected', '--flash_attn', '--gradient_checkpointing', '--zero_stage', '2'] exits with return code = 1

不知道是什么错

**Comment by chuangzhidan** [comment]
降级falsh_attn版本,没有再报错了
