### ISSUE TITLE
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer')) 使用readme示例中的"使用 Ray 和 vLLM 的 PPO"报错

### ISSUE THREAD

**Issue by chuangzhidan** [OpenRLHF/OpenRLHF#628]
**使用readme示例中的"使用 Ray 和 vLLM 的 PPO"报错，主要是改了模型为Qwen测试下。单节点2张A800**,vLLM没安装，不知道这个有没有影响

root@2e7b3294432c:/workspace/OpenRLHF# ray job submit --address="http://127.0.0.1:8265" \
  --runtime-env-json='{"working_dir": "/openrlhf"}' \
  -- python3 -m openrlhf.cli.train_ppo_ray \
  --ref_num_nodes 1 \
  --ref_num_gpus_per_node 2 \
  --reward_num_nodes 1 \
  --reward_num_gpus_per_node 2 \
  --critic_num_nodes 1 \
  --critic_num_gpus_per_node 2 \
  --actor_num_nodes 1 \
  --actor_num_gpus_per_node 2 \
  --vllm_num_engines 2 \
  --vllm_tensor_parallel_size 2 \
  --colocate_critic_reward \
  --colocate_actor_ref \
  **--pretrain /media/data/llm/Qwen2.5-0.5B-Instruct \
  --reward_pretrain /media/data/llm/Qwen2.5-0.5B-Instruct \
  --save_path /openrlhf/examples/checkpoint/Qwen2.5-0.5B-rlhf \**
  --micro_train_batch_size 4 \
  --train_batch_size 64 \
  --micro_rollout_batch_size 16 \
  --rollout_batch_size 512 \
  --max_samples 1000 \
  --max_epochs 1 \
  --prompt_max_len 1024 \
  --generate_max_len 1024 \
  --zero_stage 2 \
  --bf16 \
  --actor_learning_rate 5e-7 \
  --critic_learning_rate 9e-6 \
  --init_kl_coef 0.01 \
  --prompt_data OpenRLHF/prompt-collection-v0.1 \
  --input_key context_messages \
  --apply_chat_template \
  --normalize_reward \
  --packing_samples \
  --adam_offload \
  --flash_attn \
  --gradient_checkpointing \
  --load_checkpoint
Job submission server address: http://127.0.0.1:8265
2024-12-26 07:39:32,044	INFO dashboard_sdk.py:338 -- Uploading package gcs://_ray_pkg_b98b118e47694ab9.zip.
2024-12-26 07:39:32,046	INFO packaging.py:530 -- Creating a file package for local directory '/openrlhf'.
2024-12-26 07:39:32,048	WARNING packaging.py:405 -- File /openrlhf/sgz/ikasrca.tar.gz is very large (548.49MiB). Consider adding this file to the 'excludes' list to skip uploading it: `ray.init(..., runtime_env={'excludes': ['/openrlhf/sgz/ikasrca.tar.gz']})`
2024-12-26 07:39:33,502	WARNING packaging.py:405 -- File /openrlhf/sgz/yjj.tar.gz is very large (500.18MiB). Consider adding this file to the 'excludes' list to skip uploading it: `ray.init(..., runtime_env={'excludes': ['/openrlhf/sgz/yjj.tar.gz']})`
 ·············
list to skip uploading it: `ray.init(..., runtime_env={'excludes': ['/openrlhf/.local/lib/python3.12/site-packages/fiona.libs/libgdal-fiona-e8f6bdb0.so.35.3.9.2']})`
2024-12-26 07:41:45,798	WARNING packaging.py:405 -- File /openrlhf/.local/lib/python3.12/site-packages/grpc/_cython/cygrpc.cpython-312-x86_64-linux-gnu.so is very large (12.63MiB). Consider adding this file to the 'excludes' list to skip uploading it: `ray.init(..., runtime_env={'excludes': ['/openrlhf/.local/lib/python3.12/site-packages/grpc/_cython/cygrpc.cpython-312-x86_64-linux-gnu.so']})`
2024-12-26 07:41:46,777	WARNING packaging.py:405 -- File /openrlhf/.local/lib/python3.12/site-packages/numpy.libs/libopenblas64_p-r0-0cf96a72.3.23.dev.so is very large (33.50MiB). Consider adding this file to the 'excludes' list to skip uploading it: `ray.init(..., runtime_env={'excludes': ['/openrlhf/.local/lib/python3.12/site-packages/numpy.libs/libopenblas64_p-r0-0cf96a72.3.23.dev.so']})`
2024-12-26 07:41:48,210	WARNING packaging.py:405 -- File /openrlhf/.local/lib/python3.10/site-packages/faiss/_swigfaiss.cpython-310-x86_64-linux-gnu.so is very large (147.11MiB). Consider adding this file to the 'excludes' list to skip uploading it: `ray.init(..., runtime_env={'excludes': ['/openrlhf/.local/lib/python3.10/site-packages/faiss/_swigfaiss.cpython-310-x86_64-linux-gnu.so']})`
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py", line 791, in urlopen
    response = self._make_request(
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py", line 497, in _make_request
    conn.request(
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connection.py", line 409, in request
    self.send(chunk)
  File "/usr/lib/python3.10/http/client.py", line 999, in send
    self.sock.sendall(data)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py", line 845, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.10/dist-packages/urllib3/util/retry.py", line 470, in increment
    raise reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.10/dist-packages/urllib3/util/util.py", line 38, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py", line 791, in urlopen
    response = self._make_request(
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py", line 497, in _make_request
    conn.request(
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connection.py", line 409, in request
    self.send(chunk)
  File "/usr/lib/python3.10/http/client.py", line 999, in send
    self.sock.sendall(data)
**urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))**

**Comment by hijkzzz** [comment]
肯定要装 vllm

**Comment by chuangzhidan** [comment]
> 肯定要装 vllm

好的，但是装了，发现还是一样的报错
root@2e7b3294432c:/workspace/OpenRLHF# pip show vllm
Name: vllm
Version: 0.6.5
Summary: A high-throughput and memory-efficient inference and serving engine for LLMs
Home-page: https://github.com/vllm-project/vllm
Author: vLLM Team
Author-email: 
License: Apache 2.0
Location: /usr/local/lib/python3.10/dist-packages
Requires: aiohttp, blake3, compressed-tensors, depyf, einops, fastapi, filelock, gguf, importlib_metadata, lm-format-enforcer, mistral_common, msgspec, numpy, nvidia-ml-py, openai, outlines, partial-json-parser, pillow, prometheus-fastapi-instrumentator, prometheus_client, protobuf, psutil, py-cpuinfo, pydantic, pyyaml, pyzmq, ray, requests, sentencepiece, tiktoken, tokenizers, torch, torchvision, tqdm, transformers, typing_extensions, uvicorn, xformers, xgrammar
Required-by:

**Comment by pizts** [comment]
我的理解是，运行的时候会将设置的runtime-env文件夹拷贝到tmp一份，你的训练数据放到了设置的runtime-env文件夹下，导致拷贝时文件太大报错，你得把训练集换个不是runtime-env的文件夹应该就可以了。
