### ISSUE TITLE
循环导入，不知道哪个文件命名重复导致的错误

### ISSUE THREAD

**Issue by chuangzhidan** [OpenRLHF/OpenRLHF#638]
循环导入，不知道哪个文件命名重复导致的错误
root@2e7b3294432c:/workspace/OpenRLHF# ray job submit --address="http://127.0.0.1:8265" --runtime-env-json='{  "working_dir": **"/workspace/OpenRLHF/openrlhf"}'**   -- python3 -m openrlhf.cli.train_ppo_ray   --ref_num_nodes 1   --ref_num_gpus_per_node 2   --reward_num_nodes 1   --reward_num_gpus_per_node 2   --critic_num_nodes 1   --critic_num_gpus_per_node 2   --actor_num_nodes 1   --actor_num_gpus_per_node 2   --vllm_num_engines 2   --vllm_tensor_parallel_size 2   --colocate_critic_reward   --colocate_actor_ref   --pretrain /media/data/llm/Qwen2.5-0.5B-Instruct   --reward_pretrain /media/data/llm/Qwen2.5-0.5B-Instruct   --save_path /openrlhf/examples/checkpoint/Qwen2.5-0.5B-rlhf   --micro_train_batch_size 4   --train_batch_size 32   --micro_rollout_batch_size 16   --rollout_batch_size 256   --max_samples 1000   --max_epochs 1   --prompt_max_len 1024   --generate_max_len 1024   --zero_stage 2   --bf16   --actor_learning_rate 5e-7   --critic_learning_rate 9e-6   --init_kl_coef 0.01   --prompt_data OpenRLHF/prompt-collection-v0.1   --input_key context_messages   --apply_chat_template   --normalize_reward   --packing_samples   --adam_offload   --flash_attn   --gradient_checkpointing   --load_checkpoint
Job submission server address: http://127.0.0.1:8265
2024-12-30 02:54:40,547	INFO dashboard_sdk.py:338 -- Uploading package gcs://_ray_pkg_da569a350435fab9.zip.
2024-12-30 02:54:40,548	INFO packaging.py:530 -- Creating a file package for local directory '/workspace/OpenRLHF/openrlhf'.

-------------------------------------------------------
Job 'raysubmit_MVj8T38DRakX1dxf' submitted successfully
-------------------------------------------------------

Next steps
  Query the logs of the job:
    ray job logs raysubmit_MVj8T38DRakX1dxf
  Query the status of the job:
    ray job status raysubmit_MVj8T38DRakX1dxf
  Request the job to be stopped:
    ray job stop raysubmit_MVj8T38DRakX1dxf

Tailing logs until the job exits (disable with --no-wait):
[2024-12-30 02:55:08,110] [INFO] [real_accelerator.py:203:get_accelerator] Setting ds_accelerator to cuda (auto detect)
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/workspace/OpenRLHF/openrlhf/cli/train_ppo_ray.py", line 9, in <module>
    from openrlhf.trainer.ray import (
  File "/workspace/OpenRLHF/openrlhf/trainer/__init__.py", line 1, in <module>
    from .dpo_trainer import DPOTrainer
  File "/workspace/OpenRLHF/openrlhf/trainer/dpo_trainer.py", line 10, in <module>
    from openrlhf.models import DPOLoss
  File "/workspace/OpenRLHF/openrlhf/models/__init__.py", line 14, in <module>
    from .model import get_llm_for_sequence_regression
  File "/workspace/OpenRLHF/openrlhf/models/model.py", line 12, in <module>
    from openrlhf.utils.logging_utils import init_logger
  File "/workspace/OpenRLHF/openrlhf/utils/__init__.py", line 2, in <module>
    from .utils import blending_datasets, get_strategy, get_tokenizer
  File "/workspace/OpenRLHF/openrlhf/utils/utils.py", line 3, in <module>
    from datasets import interleave_datasets, load_dataset, load_from_disk
  File "/tmp/ray/session_2024-12-27_07-51-19_644705_918/runtime_resources/working_dir_files/_ray_pkg_da569a350435fab9/datasets/__init__.py", line 1, in <module>
    from .process_reward_dataset import ProcessRewardDataset
  File "/tmp/ray/session_2024-12-27_07-51-19_644705_918/runtime_resources/working_dir_files/_ray_pkg_da569a350435fab9/datasets/process_reward_dataset.py", line 8, in <module>
    from openrlhf.utils.utils import convert_token_to_id
ImportError: cannot import name 'convert_token_to_id' from partially initialized module 'openrlhf.utils.utils' (most likely due to a circular import) (/workspace/OpenRLHF/openrlhf/utils/utils.py)

---------------------------------------
Job 'raysubmit_MVj8T38DRakX1dxf' failed
---------------------------------------

Status message: Job entrypoint command failed with exit code 1, last available logs (truncated to 20,000 chars):
    from openrlhf.utils.logging_utils import init_logger
  File "/workspace/OpenRLHF/openrlhf/utils/__init__.py", line 2, in <module>
    from .utils import blending_datasets, get_strategy, get_tokenizer
  File "/workspace/OpenRLHF/openrlhf/utils/utils.py", line 3, in <module>
    from datasets import interleave_datasets, load_dataset, load_from_disk
  File "/tmp/ray/session_2024-12-27_07-51-19_644705_918/runtime_resources/working_dir_files/_ray_pkg_da569a350435fab9/datasets/__init__.py", line 1, in <module>
    from .process_reward_dataset import ProcessRewardDataset
  File "/tmp/ray/session_2024-12-27_07-51-19_644705_918/runtime_resources/working_dir_files/_ray_pkg_da569a350435fab9/datasets/process_reward_dataset.py", line 8, in <module>
    **from openrlhf.utils.utils import convert_token_to_id
ImportError: cannot import name 'convert_token_to_id' from partially initialized module 'openrlhf.utils.utils' (most likely due to a circular import) (/workspace/OpenRLHF/openrlhf/utils/utils.py)**

**Comment by hijkzzz** [comment]
see https://github.com/OpenRLHF/OpenRLHF/issues/603

**Comment by chuangzhidan** [comment]
> see #603

**谢谢你。移除了--runtime-env-json，可以了，但是遇到磁盘空间不足的问题，不知道可不可以清理 /tmp 目录 ，删除 /tmp/ray 下的文件以释放磁盘空间？

**
-------------------------------------------------------
Job 'raysubmit_xQU5GaiMnSTxqZzZ' submitted successfully
-------------------------------------------------------

Next steps
  Query the logs of the job:
    ray job logs raysubmit_xQU5GaiMnSTxqZzZ
  Query the status of the job:
    ray job status raysubmit_xQU5GaiMnSTxqZzZ
  Request the job to be stopped:
    ray job stop raysubmit_xQU5GaiMnSTxqZzZ

Tailing logs until the job exits (disable with --no-wait):
[2024-12-30 05:28:41,556] [INFO] [real_accelerator.py:203:get_accelerator] Setting ds_accelerator to cuda (auto detect)
2024-12-30 05:28:44,157	INFO worker.py:1429 -- Using address 0.0.0.0:6379 set in the environment variable RAY_ADDRESS
2024-12-30 05:28:44,157	INFO worker.py:1564 -- Connecting to existing Ray cluster at address: 0.0.0.0:6379...
2024-12-30 05:28:44,185	INFO worker.py:1740 -- Connected to Ray cluster. View the dashboard at 0.0.0.0:8265 
(pid=232609) [2024-12-30 05:28:50,147] [INFO] [real_accelerator.py:203:get_accelerator] Setting ds_accelerator to cuda (auto detect)
(raylet) [2024-12-30 05:28:51,682 E 1256 1290] (raylet) file_system_monitor.cc:111: /tmp/ray/session_2024-12-27_07-51-19_644705_918 is over 95% full, available space: 133932761088; capacity: 3998267736064. Object creation will fail if spilling is required.
(pid=232805) [2024-12-30 05:28:58,635] [INFO] [real_accelerator.py:203:get_accelerator] Setting ds_accelerator to cuda (auto detect)
(pid=232806) [2024-12-30 05:28:58,838] [INFO] [real_accelerator.py:203:get_accelerator] Setting ds_accelerator to cuda (auto detect)
(raylet) [2024-12-30 05:29:01,702 E 1256 1290] (raylet) file_system_monitor.cc:111: /tmp/ray/session_2024-12-27_07-51-19_644705_918 is over 95% full, available space: 133932589056; capacity: 3998267736064. Object creation will fail if spilling is required.
(pid=233132) [2024-12-30 05:29:07,488] [INFO] [real_accelerator.py:203:get_accelerator] Setting ds_accelerator to cuda (auto detect)
(raylet) [2024-12-30 05:29:11,719 E 1256 1290] (raylet) file_system_monitor.cc:111: /tmp/ray/session_2024-12-27_07-51-19_644705_918 is over 95% full, available space: 133932650496; capacity: 3998267736064. Object creation will fail if spilling is required.
(raylet) [2024-12-30 05:29:21,736 E 1256 1290] (raylet) file_system_monitor.cc:111: /tmp/ray/session_2024-12-27_07-51-19_644705_918 is over 95% full, available space: 133932646400; capacity: 3998267736064. Object creation will fail if spilling is required.
(raylet) [2024-12-30 05:29:31,752 E 1256 1290] (raylet) file_system_monitor.cc:111: /tmp/ray/session_2024-12-27_07-51-19_644705_918 is over 95% full, available space: 133932347392; capacity: 3998267736064. Object creation will fail if spilling is required.
(raylet) [2024-12-30 05:29:41,769 E 1256 1290] (raylet) file_system_monitor.cc:111: /tmp/ray/session_2024-12-27_07-51-19_644705_918 is over 95% full, available space: 133932335104; capacity: 3998267736064. Object creation will fail if spilling is required.
(raylet) [2024-12-30 05:29:51,785 E 1256 1290] (raylet) file_system_monitor.cc:111: /tmp/ray/session_2024-12-27_07-51-19_644705_918 is over 95% full, available space: 133932859392; capacity: 3998267736064. Object creation will fail if spilling is required.
(raylet) [2024-12-30 05:30:01,802 E 1256 1290] (raylet) file_system_monitor.cc:111: /tmp/ray/session_2024-12-27_07-51-19_644705_918 is over 95% full, available space: 1················
