### ISSUE TITLE
try kd a Qwen2.5-14B model to a Qwen2.5-7B met with OOM

### ISSUE THREAD

**Issue by chuangzhidan** [OpenRLHF/OpenRLHF#641]
root@2e7b3294432c:/workspace/OpenRLHF# deepspeed   --include localhost:0,1 --module openrlhf.cli.train_kd    --max_len 512    --dataset O1-OPEN/OpenO1-SFT    --input_key instruction    --output_key output    --input_template $'User: {}\nAssistant: '    --**train_batch_size 2    --micro_train_batch_size 1**    --max_samples 5000    -**-pretrain /media/data/llm/Qwen2.5-7B-Instruct    --teacher_model /media/data/llm/Qwen2.5-14B-Instruct**    --save_path ./checkpoint/Qwen2.5-7B-kd    --save_steps -1    --logging_steps 1    --eval_steps -1    --zero_stage 3    --max_epochs 1    --bf16       --kd_coef 0.4    --learning_rate 5e-6    --gradient_checkpointing

[2024-12-30 16:11:16,994] [INFO] [config.py:1003:print]   zero_optimization_stage ...... 3
[2024-12-30 16:11:16,994] [INFO] [config.py:989:print_user_config]   json = {
    "steps_per_print": 100, 
    "zero_optimization": {
        "stage": 3, 
        "stage3_param_persistence_threshold": "auto", 
        "offload_param": {
            "device": "none", 
            "pin_memory": true
        }
    }, 
    "bf16": {
        "enabled": true
    }, 
    "gradient_clipping": 1.0, 
    "prescale_gradients": false, 
    "wall_clock_breakdown": false, 
    "train_micro_batch_size_per_gpu": 1, 
    "train_batch_size": 2
}
Train epoch:   0%|                                                                                                                                                                                  | 0/1 [00:00<?, ?it/s[rank0]: Traceback (most recent call last):                                                                                                                                                       | 0/2500 [00:00<?, ?it/s]
[rank0]:   File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
[rank0]:     return _run_code(code, main_globals, None,
[rank0]:   File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
[rank0]:     exec(code, run_globals)
[rank0]:   File "/workspace/OpenRLHF/openrlhf/cli/train_kd.py", line 229, in <module>
[rank0]:     train(args)
[rank0]:   File "/workspace/OpenRLHF/openrlhf/cli/train_kd.py", line 134, in train
[rank0]:     trainer.fit(args, consumed_samples, num_update_steps_per_epoch)
[rank0]:   File "/workspace/OpenRLHF/openrlhf/trainer/kd_trainer.py", line 153, in fit
[rank0]:     self.strategy.optimizer_step(self.optimizer, self.model, self.scheduler)
[rank0]:   File "/workspace/OpenRLHF/openrlhf/utils/deepspeed/deepspeed.py", line 141, in optimizer_step
[rank0]:     model.step()
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/deepspeed/runtime/engine.py", line 2213, in step
[rank0]:     self._take_model_step(lr_kwargs)
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/deepspeed/runtime/engine.py", line 2119, in _take_model_step
[rank0]:     self.optimizer.step()
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/deepspeed/utils/nvtx.py", line 18, in wrapped_fn
[rank0]:     ret_val = func(*args, **kwargs)
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/deepspeed/runtime/zero/stage3.py", line 2077, in step
[rank0]:     self._prepare_sub_group(sub_group_id, timer_names)
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/deepspeed/utils/nvtx.py", line 18, in wrapped_fn
[rank0]:     ret_val = func(*args, **kwargs)
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/deepspeed/runtime/zero/stage3.py", line 1907, in _prepare_sub_group
[rank0]:     self._prepare_fp32_grad_for_sub_group(sub_group_id)
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/deepspeed/utils/nvtx.py", line 18, in wrapped_fn
[rank0]:     ret_val = func(*args, **kwargs)
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/deepspeed/runtime/zero/stage3.py", line 1883, in _prepare_fp32_grad_for_sub_group
[rank0]:     single_grad_partition = self.flatten(self.averaged_gradients[sub_group_id]).to(
[rank0]: torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 3.78 GiB. GPU 0 has a total capacity of 79.25 GiB of which 375.12 MiB is free. Including non-PyTorch memory, this process has 0 bytes memory in use. Of the allocated memory 60.35 GiB is allocated by PyTorch, and 3.40 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
[rank1]: Traceback (most recent call last):
[rank1]:   File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
[rank1]:     return _run_code(code, main_globals, None,
[rank1]:   File "/usr/lib/python3.10/runpy.py", lin

[rank1]:   File "/usr/local/lib/python3.10/dist-packages/deepspeed/ops/adam/fused_adam.py", line 157, in step
[rank1]:     state['exp_avg_sq'] = torch.zeros_like(p.data)
[rank1]: torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 2.88 GiB. GPU 1 has a total capacity of 79.25 GiB of which 1.17 GiB is free. Including non-PyTorch memory, this process has 0 bytes memory in use. Of the allocated memory 71.77 GiB is allocated by PyTorch, and 2.42 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
**Train epoch:   0%|**                                                                                                                                                                                  | 0/1 [00:06<?, ?it/s]
Train step of epoch 0:   0%|                                                                                                                                                                     | 0/2500 [00:06<?, ?it/s]
[2024-12-30 16:11:26,205] [INFO] [launch.py:319:sigkill_handler] Killing subprocess 609121
[2024-12-30 16:11:26,206] [INFO] [launch.py:319:sigkill_handler] Killing subprocess 609122
[2024-12-30 16:11:26,225] [ERROR] [launch.py:325:sigkill_handler] ['/usr/bin/python', '-u', '-m', 'openrlhf.cli.train_kd', '--local_rank=1', '--max_len', '512', '--dataset', 'O1-OPEN/OpenO1-SFT', '--input_key', 'instruction', '--output_key', 'output', '--input_template', 'User: {}\nAssistant: ', '--train_batch_size', '2', '--micro_train_batch_size', '1', '--max_samples', '5000', '--pretrain', '/media/data/llm/Qwen2.5-7B-Instruct', '--teacher_model', '/media/data/llm/Qwen2.5-14B-Instruct', '--save_path', './checkpoint/Qwen2.5-7B-kd', '--save_steps', '-1', '--logging_steps', '1', '--eval_steps', '-1', '--zero_stage', '3', '--max_epochs', '1', '--bf16', '--kd_coef', '0.4', '--learning_rate', '5e-6', '--gradient_checkpointing'] exits with return code = 1

not sure how much memory needed, is there any configuration or parameter i can set to lower memory usage? 

thank u !!!!!

**Comment by hijkzzz** [comment]
use --adam_offload

**Comment by chuangzhidan** [comment]
why didn't i think of that ?  thank u so much !  love u

**Comment by chuangzhidan** [comment]
> use --adam_offload

Train epoch: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [09:28<00:00, 568.32s/it]
Train step of epoch 0: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████| 250/250 [09:28<00:00, 20.21s/it, gpt_loss=0.686, distil_loss=0.9, loss_mean=0.575, lr=5e-7


it's stuck  in this status ,do not know why ,  similar to issue #585?
--save_path ./checkpoint/Qwen2.5-7B-kd  is in the project ,but not under openrlhf  directory

**Comment by chuangzhidan** [comment]
> > use --adam_offload
> 
> Train epoch: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [09:28<00:00, 568.32s/it] Train step of epoch 0: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████| 250/250 [09:28<00:00, 20.21s/it, gpt_loss=0.686, distil_loss=0.9, loss_mean=0.575, lr=5e-7
> 
> [rank1]:[E1231 05:45:37.153774658 ProcessGroupNCCL.cpp:1484] [PG ID 0 PG GUID 0(default_pg) Rank 1] ProcessGroupNCCL's watchdog got stuck for 480 seconds without making progress in monitoring enqueued collectives. This typically indicates a NCCL/CUDA API (e.g., CudaEventDestroy) hang blocking the watchdog, and could be triggered by another thread holding the GIL inside a CUDA api (for example, CudaEventDestroy), or other deadlock-prone behaviors.If you suspect the watchdog is not actually stuck and a longer timeout would help, you can either increase the timeout (TORCH_NCCL_HEARTBEAT_TIMEOUT_SEC) to a larger value or disable the heartbeat monitor (TORCH_NCCL_ENABLE_MONITORING=0).If either of aforementioned helps, feel free to file an issue to PyTorch about the short timeout or false positive abort; otherwise, please attempt to debug the hang
> 
> seems training's completed but it got stuck in this status ,do not know why , similar to issue #585? --save_path ./checkpoint/Qwen2.5-7B-kd is in the project ,but not under openrlhf directory

**waitted nearly 30 minutes  after training.  seems all you need to do is wait.   this is a successful one?**                                                          
wandb: 
wandb: Run history:
wandb: train/distil_loss ▄█▆▁▅▃▆█▆▆▂▅▆▄▅▄▄▄▅▆▅▁▅▅▆
wandb: train/global_step ▁▁▂▂▂▂▃▃▃▄▄▄▅▅▅▅▆▆▆▇▇▇▇██
wandb:    train/gpt_loss ▅█▇▂▄▄▅▆▄▄▂▄▄▃▄▃▃▃▄▄▃▁▃▄▅
wandb:   train/loss_mean ▁▂▃▄▄▅▅▆▆▆▆▇▇▇▇▇▇████████
wandb:          train/lr █████▇▇▇▆▆▅▅▅▄▄▃▃▂▂▂▁▁▁▁▁
wandb: 
wandb: Run summary:
wandb: train/distil_loss 0.90026
wandb: train/global_step 25
wandb:    train/gpt_loss 0.68555
wandb:   train/loss_mean 0.57484
wandb:          train/lr 0.0
wandb: 
wandb: 🚀 View run sft_1231T05:21 at: https://wandb.ai/gavinteam/openrlhf_train_sft/runs/tumhupo9
wandb: ⭐️ View project at: https://wandb.ai/gavinteam/openrlhf_train_sft
wandb: Synced 5 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)
wandb: Find logs at: ./wandb/run-20241231_052317-tumhupo9/logs
/usr/local/lib/python3.10/dist-packages/wandb/sdk/wandb_run.py:2299: UserWarning: Run (tumhupo9) is finished. The call to `_console_raw_callback` will be ignored. Please make sure that you are using an active run.
  lambda data: self._console_raw_callback("stderr", data),
Train epoch: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [29:25<00:00, 1765.71s/it]
Train step of epoch 0: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████| 25/25 [29:25<00:00, 70.63s/it, gpt_loss=0.686, distil_loss=0.9, loss_mean=0.575, lr=5e-7]
[2024-12-31 05:53:04,742] [INFO] [launch.py:351:main] Process 757526 exits successfully.
[2024-12-31 05:57:04,966] [INFO] [launch.py:351:main] Process 757525 exits successfully.
