### ISSUE TITLE
reward模型训练完怎么用于ppo

### ISSUE THREAD

**Issue by Curisan** [OpenRLHF/OpenRLHF#643]
请教下，reward模型训练完成后怎么用于ppo模型训练，直接设置reward_pretrain会有问题。

**Comment by hijkzzz** [comment]
什么问题 就是这样用的

**Comment by Curisan** [comment]
Some weights of CriticModel were not initialized from the model checkpoint at **** and are newly initialized: ['score.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
[rank0]: Traceback (most recent call last):
[rank0]:   File "/data1/yezj/miniconda3/envs/openrlhf/lib/python3.10/runpy.py", line 196, in _run_module_as_main
[rank0]:     return _run_code(code, main_globals, None,
[rank0]:   File "/data1/yezj/miniconda3/envs/openrlhf/lib/python3.10/runpy.py", line 86, in _run_code
[rank0]:     exec(code, run_globals)
[rank0]:   File "/data1/yezj/miniconda3/envs/openrlhf/lib/python3.10/site-packages/openrlhf/cli/train_ppo.py", line 439, in <module>
[rank0]:     train(args)
[rank0]:   File "/data1/yezj/miniconda3/envs/openrlhf/lib/python3.10/site-packages/openrlhf/cli/train_ppo.py", line 39, in train
[rank0]:     critic = get_llm_for_sequence_regression(
[rank0]:   File "/data1/yezj/miniconda3/envs/openrlhf/lib/python3.10/site-packages/openrlhf/models/model.py", line 102, in get_llm_for_sequence_regression
[rank0]:     model = cls_class.from_pretrained(
[rank0]:   File "/data1/yezj/miniconda3/envs/openrlhf/lib/python3.10/site-packages/transformers/modeling_utils.py", line 4310, in from_pretrained
[rank0]:     model.load_adapter(
[rank0]:   File "/data1/yezj/miniconda3/envs/openrlhf/lib/python3.10/site-packages/transformers/integrations/peft.py", line 233, in load_adapter
[rank0]:     incompatible_keys = set_peft_model_state_dict(
[rank0]:   File "/data1/yezj/miniconda3/envs/openrlhf/lib/python3.10/site-packages/peft/utils/save_and_load.py", line 451, in set_peft_model_state_dict
[rank0]:     load_result = model.load_state_dict(peft_model_state_dict, strict=False)
[rank0]:   File "/data1/yezj/miniconda3/envs/openrlhf/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2215, in load_state_dict
[rank0]:     raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
[rank0]: RuntimeError: Error(s) in loading state_dict for CriticModel:
[rank0]: 	size mismatch for model.layers.0.mlp.gate_proj.lora_B.default.weight: copying a param with shape torch.Size([0]) from checkpoint, the shape in current model is torch.Size([18944, 8]).
[rank0]: 	size mismatch for model.layers.0.mlp.up_proj.lora_B.default.weight: copying a param with shape torch.Size([0]) from checkpoint, the shape in current model is torch.Size([18944, 8]).
[rank0]: 	size mismatch for model.layers.0.mlp.down_proj.lora_A.default.weight: copying a param with shape torch.Size([0]) from checkpoint, the shape in current model is torch.Size([8, 18944]).
[rank0]: 	size mismatch for model.layers.1.mlp.gate_proj.lora_B.default.weight: copying a param with shape torch.Size([0]) from checkpoint, the shape in current model is torch.Size([18944, 8]).
[rank0]: 	size mismatch for model.layers.1.mlp.up_proj.lora_B.default.weight: copying a param with shape torch.Size([0]) from checkpoint, the shape in current model is torch.Size([18944, 8]).
[rank0]: 	size mismatch for model.layers.1.mlp.down_proj.lora_A.default.weight: copying a param with shape torch.Size([0]) from checkpoint, the shape in current model is torch.Size([8, 18944]).
[rank0]: 	size mismatch for model.layers.2.mlp.gate_proj.lora_B.default.weight: copying a param with shape torch.Size([0]) from checkpoint, the shape in current model is torch.Size([18944, 8]).
[rank0]: 	size mismatch for model.layers.2.mlp.up_proj.lora_B.default.weight: copying a param with shape torch.Size([0]) from checkpoint, the shape in current model is torch.Size([18944, 8]).
[rank0]: 	size mismatch for model.layers.2.mlp.down_proj.lora_A.default.weight: copying a param with shape torch.Size([0]) from checkpoint, the shape in current model is torch.Size([8, 18944]).
[rank0]: 	size mismatch for model.layers.3.mlp.gate_proj.lora_B.default.weight: copying a param with shape torch.Size([0]) from checkpoint, the shape in current model is torch.Size([18944, 8]).
[rank0]: 	size mismatch for model.layers.3.mlp.up_proj.lora_B.default.weight: copying a param with shape torch.Size([0]) from checkpoint, the shape in current model is torch.Size([18944, 8]).

reward模型是用lora训练的。

**Comment by LinXueyuanStdio** [comment]
我知道这个错误，把 '--gradient_checkpointing' 去掉就好了

**Comment by ZinYY** [comment]
> 我知道这个错误，把 '--gradient_checkpointing' 去掉就好了

Hi, I'm encountering the same issue. However, removing --gradient_checkpointing from the PPO training still doesn't resolve it. 😭

**Comment by hijkzzz** [comment]
Fixed in https://github.com/OpenRLHF/OpenRLHF/commit/18010bca5ff6cfe0cde4cf654efa180e1d28afe9
